import { CertificateTypeConfig } from "./types";

export const MVP_CERTIFICATES: CertificateTypeConfig[] = [
  // --- REGISTRO CIVIL ---
  {
    id: "nascimento",
    slug: "certidao-de-nascimento",
    name: "Certidão de Nascimento",
    shortDescription: "2ª via oficial de nascimento com validade jurídica nacional em formato digital ou papel moeda.",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 129.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "registeredName", label: "Nome Completo do Registrado", type: "text", required: true, placeholder: "Ex: João da Silva Santos" },
      { id: "birthDate", label: "Data de Nascimento", type: "date", required: true },
      { id: "fatherName", label: "Nome Completo do Pai", type: "text", required: false, placeholder: "Ex: Carlos Eduardo Santos" },
      { id: "motherName", label: "Nome Completo da Mãe", type: "text", required: true, placeholder: "Ex: Maria Helena da Silva" },
      { id: "cpf", label: "CPF do Registrado (se houver)", type: "text", required: false, placeholder: "000.000.000-00" },
      { id: "bookNumber", label: "Livro (opcional)", type: "text", required: false, placeholder: "Ex: A-123" },
      { id: "pageNumber", label: "Folha (opcional)", type: "text", required: false, placeholder: "Ex: 45v" },
      { id: "termNumber", label: "Termo / Registro (opcional)", type: "text", required: false, placeholder: "Ex: 12345" },
    ],
  },
  {
    id: "casamento",
    slug: "certidao-de-casamento",
    name: "Certidão de Casamento",
    shortDescription: "2ª via oficial de certidão de casamento com averbações (divórcio, alteração de nome, etc.).",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 139.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "spouse1Name", label: "Nome do Cônjuge 1 (Nome de Solteiro/a)", type: "text", required: true, placeholder: "Ex: Marcos Paulo Oliveira" },
      { id: "spouse2Name", label: "Nome do Cônjuge 2 (Nome de Solteiro/a)", type: "text", required: true, placeholder: "Ex: Ana Beatriz Ferreira" },
      { id: "marriageDate", label: "Data do Casamento", type: "date", required: true },
      { id: "bookNumber", label: "Livro (opcional)", type: "text", required: false, placeholder: "Ex: B-45" },
      { id: "pageNumber", label: "Folha (opcional)", type: "text", required: false, placeholder: "Ex: 12" },
      { id: "termNumber", label: "Termo (opcional)", type: "text", required: false, placeholder: "Ex: 9876" },
    ],
  },
  {
    id: "obito",
    slug: "certidao-de-obito",
    name: "Certidão de Óbito",
    shortDescription: "2ª via de certidão de óbito indispensável para inventários, heranças, partilhas e encerramentos.",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 139.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "deceasedName", label: "Nome do Falecido(a)", type: "text", required: true, placeholder: "Ex: Geraldo José de Souza" },
      { id: "deathDate", label: "Data do Falecimento", type: "date", required: true },
      { id: "cpf", label: "CPF do Falecido(a)", type: "text", required: false, placeholder: "000.000.000-00" },
      { id: "motherName", label: "Nome da Mãe do Falecido(a)", type: "text", required: false, placeholder: "Ex: Laura Souza" },
      { id: "bookNumber", label: "Livro (opcional)", type: "text", required: false },
      { id: "pageNumber", label: "Folha (opcional)", type: "text", required: false },
      { id: "termNumber", label: "Termo (opcional)", type: "text", required: false },
    ],
  },

  // --- TABELIONATO DE NOTAS ---
  {
    id: "testamento",
    slug: "certidao-negativa-de-testamento",
    name: "Certidão Negativa de Testamento (CENSEC)",
    shortDescription: "Busca na Central Notarial de Serviços Compartilhados (CENSEC) obrigatória para inventários judiciais e extrajudiciais.",
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 119.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "deceasedName", label: "Nome Completo do Falecido(a)", type: "text", required: true, placeholder: "Ex: Antônio Carlos Pereira" },
      { id: "deceasedCpf", label: "CPF do Falecido(a)", type: "text", required: true, placeholder: "000.000.000-00" },
      { id: "deceasedRg", label: "RG do Falecido(a)", type: "text", required: false, placeholder: "00.000.000-0" },
      { id: "deathDate", label: "Data do Falecimento", type: "date", required: true },
      { id: "fatherName", label: "Nome do Pai", type: "text", required: false },
      { id: "motherName", label: "Nome da Mãe", type: "text", required: true },
    ],
  },
  {
    id: "escritura",
    slug: "certidao-de-escritura",
    name: "Certidão de Escritura Pública",
    shortDescription: "2ª via de escritura de Compra e Venda, Doação, Inventário, Divórcio ou Declaração Notarial.",
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 169.90,
    estimatedDays: "3 a 6 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 40.00,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "deedType", label: "Tipo de Escritura", type: "select", required: true, options: [
        { label: "Compra e Venda", value: "compra_venda" },
        { label: "Doação", value: "doacao" },
        { label: "Inventário e Partilha", value: "inventario" },
        { label: "Divórcio / Dissolução", value: "divorcio" },
        { label: "Pacto Antenupcial", value: "pacto_antenupcial" },
        { label: "União Estável", value: "uniao_estavel" },
        { label: "Outros", value: "outros" },
      ]},
      { id: "grantorName", label: "Nome de uma das Partes (Outorgante ou Outorgado)", type: "text", required: true, placeholder: "Ex: Roberto Silveira" },
      { id: "cpfParty", label: "CPF de uma das Partes", type: "text", required: false, placeholder: "000.000.000-00" },
      { id: "bookNumber", label: "Livro de Notas (se souber)", type: "text", required: false },
      { id: "pageNumber", label: "Página / Folha (se souber)", type: "text", required: false },
    ],
  },

  // --- REGISTRO DE IMÓVEIS ---
  {
    id: "matricula-imovel",
    slug: "certidao-de-matricula-de-imovel",
    name: "Certidão de Matrícula de Imóvel (Inteiro Teor com Ônus e Ações)",
    shortDescription: "Certidão oficial do imóvel com histórico completo de proprietários, averbações, hipotecas, penhoras e ônus.",
    category: "imoveis",
    categoryName: "Registro de Imóveis",
    basePrice: 189.90,
    estimatedDays: "2 a 4 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 45.00,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "matriculaNumber", label: "Número da Matrícula ou Transcrição", type: "text", required: false, placeholder: "Ex: 123.456 (se não souber, preencha o endereço)" },
      { id: "propertyAddress", label: "Endereço Completo do Imóvel", type: "text", required: true, placeholder: "Rua, Número, Apto/Bloco, Bairro" },
      { id: "ownerName", label: "Nome do Proprietário Atual ou Anterior", type: "text", required: false, placeholder: "Ex: Construtora Horizon Ltda" },
      { id: "ownerCpfCnpj", label: "CPF/CNPJ do Proprietário", type: "text", required: false, placeholder: "00.000.000/0000-00" },
    ],
  },

  // --- TABELIONATO DE PROTESTO ---
  {
    id: "protesto",
    slug: "certidao-de-protesto",
    name: "Certidão de Protesto (Negativa / Positiva)",
    shortDescription: "Comprova existência ou inexistência de títulos protestados (dívidas, duplicatas, cheques e notas promissórias).",
    category: "protesto",
    categoryName: "Tabelionato de Protesto",
    basePrice: 119.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: true,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: [
      { id: "personName", label: "Nome ou Razão Social a ser Pesquisado", type: "text", required: true, placeholder: "Ex: Empresa XYZ Ltda ou Nome da Pessoa" },
      { id: "cpfCnpj", label: "CPF ou CNPJ", type: "text", required: true, placeholder: "000.000.000-00 ou 00.000.000/0000-00" },
      { id: "period", label: "Período de Busca", type: "select", required: true, options: [
        { label: "Últimos 5 Anos (Padrão)", value: "5_anos" },
        { label: "Últimos 10 Anos", value: "10_anos" },
      ]},
    ],
  },
];

export function getCertificateBySlug(slug: string): CertificateTypeConfig | undefined {
  return MVP_CERTIFICATES.find((item) => item.slug === slug);
}
