import { CRC_FORM_FIELDS } from "./crc-form-fields";
import { CertificateTypeConfig } from "./types";

function escrituraPublica(
  slug: string,
  name: string,
  shortDescription: string
): CertificateTypeConfig {
  return {
    id: slug.replace(/^certidao-de-escritura-de-/, "escritura-"),
    slug,
    name,
    shortDescription,
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 219.9,
    estimatedDays: "3 a 6 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 40,
    hasApostilleOption: true,
    apostillePrice: 110,
    hasShippingOption: true,
    shippingPrice: 32,
    fields: CRC_FORM_FIELDS[slug] ?? [],
  };
}

const ESCRITURAS_PUBLICAS: CertificateTypeConfig[] = [
  escrituraPublica(
    "certidao-de-escritura-de-ata-notarial",
    "Certidão de Escritura de Ata Notarial",
    "2ª via da ata notarial lavrada em tabelionato de notas, com fé pública sobre fatos, declarações ou constatação."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-cessao-de-direito-de-imovel",
    "Certidão de Escritura de Cessão de Direito de Imóvel",
    "2ª via da escritura de cessão de direitos sobre imóvel, usada em transmissões e regularização de posse."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-compra-e-venda",
    "Certidão de Escritura de Compra e Venda",
    "2ª via da escritura pública de compra e venda de imóvel lavrada em tabelionato de notas."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-divorcio",
    "Certidão de Escritura de Divórcio",
    "2ª via da escritura pública de divórcio consensual lavrada em tabelionato de notas."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-doacao",
    "Certidão de Escritura de Doação",
    "2ª via da escritura pública de doação de bens, com doador, donatário e objeto da liberalidade."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-emancipacao",
    "Certidão de Escritura de Emancipação",
    "2ª via da escritura que concede capacidade civil plena a menores entre 16 e 18 anos."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-hipoteca",
    "Certidão de Escritura de Hipoteca",
    "2ª via da escritura pública de hipoteca, com credor, devedor e imóvel dado em garantia."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-imovel",
    "Certidão de Escritura de Imóvel",
    "2ª via de escritura pública relativa a imóvel lavrada em tabelionato de notas."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-inventario-e-partilha",
    "Certidão de Escritura de Inventário e Partilha",
    "2ª via da escritura de inventário e partilha extrajudicial, com herdeiros e bens partilhados."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-pacto-antenupcial",
    "Certidão de Escritura de Pacto Antenupcial",
    "2ª via da escritura do pacto antenupcial que define o regime de bens do casamento."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-permuta",
    "Certidão de Escritura de Permuta",
    "2ª via da escritura pública de permuta de bens, com as partes e os objetos trocados."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-registro-de-condominio",
    "Certidão de Escritura de Registro de Condomínio",
    "2ª via da escritura de instituição ou registro de condomínio lavrada em notas."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-registro-de-partilha",
    "Certidão de Escritura de Registro de Partilha",
    "2ª via da escritura de registro de partilha de bens entre herdeiros ou cônjuges."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-renuncia-de-heranca",
    "Certidão de Escritura de Renúncia de Herança",
    "2ª via da escritura em que o herdeiro renuncia à herança, com identificação das partes e do espólio."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-substabelecimento",
    "Certidão de Escritura de Substabelecimento",
    "2ª via da escritura de substabelecimento de procuração, com poderes transferidos ao substabelecido."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-uniao-estavel",
    "Certidão de Escritura de União Estável",
    "2ª via da escritura pública de reconhecimento de união estável e do regime de bens."
  ),
  escrituraPublica(
    "certidao-de-escritura-de-usucapiao",
    "Certidão de Escritura de Usucapião",
    "2ª via da ata ou escritura de usucapião extrajudicial lavrada em tabelionato de notas."
  ),
];

export const MVP_CERTIFICATES: CertificateTypeConfig[] = [
  // --- REGISTRO CIVIL ---
  {
    id: "nascimento",
    slug: "certidao-de-nascimento",
    name: "Certidão de Nascimento",
    shortDescription: "2ª via oficial de nascimento com validade jurídica nacional em formato digital ou papel moeda.",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 299.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 259.90,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-format",
    fields: CRC_FORM_FIELDS["certidao-de-nascimento"],
  },
  {
    id: "casamento",
    slug: "certidao-de-casamento",
    name: "Certidão de Casamento",
    shortDescription: "2ª via oficial de certidão de casamento com averbações (divórcio, alteração de nome, etc.).",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 299.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 259.90,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-format",
    fields: CRC_FORM_FIELDS["certidao-de-casamento"],
  },
  {
    id: "obito",
    slug: "certidao-de-obito",
    name: "Certidão de Óbito",
    shortDescription: "2ª via de certidão de óbito indispensável para inventários, heranças, partilhas e encerramentos.",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 299.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 259.90,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-format",
    fields: CRC_FORM_FIELDS["certidao-de-obito"],
  },
  {
    id: "divorcio",
    slug: "certidao-de-divorcio",
    name: "Certidão de Divórcio",
    shortDescription: "2ª via da certidão de casamento com averbação de divórcio, ou certidão específica de divórcio lavrada no registro civil.",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 299.90,
    estimatedDays: "3 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 259.90,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-format",
    fields: CRC_FORM_FIELDS["certidao-de-divorcio"],
  },
  {
    id: "interdicao",
    slug: "certidao-de-interdicao",
    name: "Certidão de Interdição",
    shortDescription: "Comprova se a capacidade civil de uma pessoa foi limitada por decisão judicial e indica o curador nomeado.",
    category: "registro-civil",
    categoryName: "Registro Civil",
    basePrice: 329.90,
    estimatedDays: "3 a 6 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 35.00,
    hasApostilleOption: true,
    apostillePrice: 259.90,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["certidao-de-interdicao"],
  },

  // --- TABELIONATO DE NOTAS ---
  {
    id: "testamento",
    slug: "certidao-negativa-de-testamento",
    name: "Certidão Negativa de Testamento (CENSEC)",
    shortDescription: "Busca na Central Notarial de Serviços Compartilhados (CENSEC) obrigatória para inventários judiciais e extrajudiciais.",
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 239.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["certidao-negativa-de-testamento"],
  },
  {
    id: "consulta-inventario",
    slug: "consulta-de-inventario",
    name: "Consulta de Inventário",
    shortDescription: "Consulta o andamento da partilha de bens após o óbito, em especial quando o inventário foi feito por escritura pública.",
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 99.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["consulta-de-inventario"],
  },
  {
    id: "inventario",
    slug: "certidao-de-inventario",
    name: "Certidão de Inventário",
    shortDescription: "2ª via da escritura de inventário que comprova a partilha de bens, direitos e dívidas deixados pelo falecido.",
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 219.90,
    estimatedDays: "3 a 6 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 40.00,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["certidao-de-inventario"],
  },
  {
    id: "procuracao",
    slug: "certidao-de-procuracao",
    name: "Certidão de Procuração",
    shortDescription: "2ª via da procuração pública lavrada em tabelionato de notas, com outorgante, outorgado e poderes.",
    category: "notas",
    categoryName: "Tabelionato de Notas",
    basePrice: 296.90,
    estimatedDays: "3 a 6 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 40.00,
    hasApostilleOption: true,
    apostillePrice: 110.00,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["certidao-de-procuracao"],
  },
  ...ESCRITURAS_PUBLICAS,

  // --- REGISTRO DE IMÓVEIS ---
  {
    id: "matricula-imovel",
    slug: "certidao-de-matricula-de-imovel",
    name: "Certidão de Matrícula de Imóvel (Inteiro Teor com Ônus e Ações)",
    shortDescription: "Certidão oficial do imóvel com histórico completo de proprietários, averbações, hipotecas, penhoras e ônus.",
    category: "imoveis",
    categoryName: "Registro de Imóveis",
    basePrice: 269.90,
    estimatedDays: "2 a 4 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 45.00,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-format",
    fields: CRC_FORM_FIELDS["certidao-de-matricula-de-imovel"],
  },
  {
    id: "busca-matricula",
    slug: "busca-da-matricula-do-imovel",
    name: "Busca da Matrícula do Imóvel",
    shortDescription: "Localiza o número da matrícula no Registro de Imóveis para depois pedir a certidão atualizada de inteiro teor.",
    category: "imoveis",
    categoryName: "Registro de Imóveis",
    basePrice: 169.90,
    estimatedDays: "2 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 45.00,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["busca-da-matricula-do-imovel"],
  },
  {
    id: "negativa-onus",
    slug: "certidao-negativa-de-onus-de-imovel",
    name: "Certidão Negativa de Ônus de Imóvel",
    shortDescription: "Declara a existência ou inexistência de hipotecas, penhoras e outros ônus sobre a matrícula.",
    category: "imoveis",
    categoryName: "Registro de Imóveis",
    basePrice: 269.90,
    estimatedDays: "2 a 4 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 45.00,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-format",
    fields: CRC_FORM_FIELDS["certidao-negativa-de-onus-de-imovel"],
  },
  {
    id: "negativa-propriedade",
    slug: "certidao-negativa-de-propriedade-imovel",
    name: "Certidão Negativa de Propriedade (Imóvel)",
    shortDescription: "Declara que a pessoa não possui imóveis registrados em seu nome na serventia pesquisada. Usada em financiamento e regularização.",
    category: "imoveis",
    categoryName: "Registro de Imóveis",
    basePrice: 255.90,
    estimatedDays: "2 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 45.00,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["certidao-negativa-de-propriedade-imovel"],
  },
  {
    id: "pesquisa-imoveis",
    slug: "pesquisa-de-imoveis",
    name: "Pesquisa de Imóveis",
    shortDescription: "Identifica imóveis vinculados a uma pessoa física ou jurídica nos Cartórios de Registro de Imóveis, a partir do CPF ou CNPJ.",
    category: "imoveis",
    categoryName: "Registro de Imóveis",
    basePrice: 169.90,
    estimatedDays: "2 a 5 dias úteis",
    requiresCartorio: true,
    hasSearchFee: true,
    searchFee: 45.00,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["pesquisa-de-imoveis"],
  },

  // --- TABELIONATO DE PROTESTO ---
  {
    id: "protesto",
    slug: "certidao-de-protesto",
    name: "Certidão de Protesto (Negativa / Positiva)",
    shortDescription: "Comprova existência ou inexistência de títulos protestados (dívidas, duplicatas, cheques e notas promissórias).",
    category: "protesto",
    categoryName: "Tabelionato de Protesto",
    basePrice: 289.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: true,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    priceMode: "uf-flat",
    fields: CRC_FORM_FIELDS["certidao-de-protesto"],
  },
  {
    id: "pesquisa-protesto",
    slug: "pesquisa-de-protesto",
    name: "Pesquisa de Protesto",
    shortDescription: "Verifica se existem protestos e em quais cartórios estão registrados, para análise de risco em crédito e transações.",
    category: "protesto",
    categoryName: "Tabelionato de Protesto",
    basePrice: 99.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["pesquisa-de-protesto"],
  },

  // --- DISTRIBUIDORES JUDICIAIS (TRF e TRT only; other CRC distributor SKUs stay out) ---
  {
    id: "trf-distribuicao",
    slug: "trf-certidao-de-distribuicao-da-justica-federal",
    name: "TRF – Certidão de Distribuição da Justiça Federal",
    shortDescription: "Informa se há processos distribuídos na Justiça Federal em nome da pessoa ou empresa. Usada em concursos, imigração, passaporte e diligências.",
    category: "distribuidores-judiciais",
    categoryName: "Distribuidores Judiciais",
    basePrice: 99.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["trf-certidao-de-distribuicao-da-justica-federal"],
  },
  {
    id: "trt-ceat",
    slug: "trt-certidao-de-acoes-trabalhistas-ceat",
    name: "TRT – Certidão de Ações Trabalhistas (CEAT)",
    shortDescription: "Informa se há ações trabalhistas registradas no TRT contra pessoa ou empresa. Usada em contratações, licitações e due diligence.",
    category: "distribuidores-judiciais",
    categoryName: "Distribuidores Judiciais",
    basePrice: 99.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["trt-certidao-de-acoes-trabalhistas-ceat"],
  },

  // CCIR: approved SKU; category `rural` is new (not RI and not distribuidores).
  {
    id: "ccir-incra",
    slug: "ccir-certificado-cadastro-imovel-rural-incra",
    name: "CCIR – Certificado de Cadastro de Imóvel Rural (INCRA)",
    shortDescription: "Documento do INCRA com dados cadastrais do imóvel rural (titularidade e localização). Exigido em compra e venda, financiamento e regularização fundiária.",
    category: "rural",
    categoryName: "Cadastro rural (INCRA)",
    basePrice: 99.90,
    estimatedDays: "1 a 3 dias úteis",
    requiresCartorio: false,
    hasSearchFee: false,
    searchFee: 0,
    hasApostilleOption: false,
    apostillePrice: 0,
    hasShippingOption: true,
    shippingPrice: 32.00,
    fields: CRC_FORM_FIELDS["ccir-certificado-cadastro-imovel-rural-incra"],
  },
];

export function getCertificateBySlug(slug: string): CertificateTypeConfig | undefined {
  if (slug === "certidao-de-escritura") {
    return MVP_CERTIFICATES.find(
      (item) => item.slug === "certidao-de-escritura-de-compra-e-venda"
    );
  }
  return MVP_CERTIFICATES.find((item) => item.slug === slug);
}
